plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false 
    alias(libs.plugins.chaquo.python) apply false
}

tasks.register('clean', Delete) {
    delete rootProject.layout.buildDirectory
}

[versions]
gson = "2.13.1"
media3 = "1.8.0"
okhttp = "5.1.0"
